### ISSUE TITLE
How do you write a driver?

### ISSUE THREAD

**Issue by trusktr** [patjak/bcwc_pcie#1]
Do you just probe it through the BUS and see what happens? Or is there some spec you can follow from broadcom? Or something else? (I've never written a OS-side driver before, just curious)

**Comment by shinglyu** [comment]
Is there anything I can help? I am a software developer. Although I'm not familiar with driver programming, but I am willing to study whatever needed to start contributing to this. 

Besides "Linux Device Drivers" and "Understanding The Linux Kernel", is there any open source driver implementation you can recommend? 

Thanks!

**Comment by patjak** [comment]
Hi @shinglyu 
We'll be writing a V4L driver for this hardware so looking at various V4L drivers is useful. But the hard part is to figure out how to drive the hardware since that is what's undocumented. Understanding how webcams work and computer hardware in general is much more helpful IMO. For instance, the ISP (Image Signal Processor) is an ARM CPU with a DSP and sensors attached. This is packaged in a SoC which is connected to the rest of the system over the PCIe bus. The logic needed for the PCIe connection seems to be the Broadcom part, hence the Broadcom PCI vendor id. I'll try to document the hardware in the wiki as work progresses but at that point I usually have already written the code. I guess there is no "read this and you know what to do" point of entry. Read up on everything you can find that seems related to the hardware and try to figure out how this particular webcam is working. Sorry but that's the best advice I can give.

**Comment by atodorov** [comment]
> There will be plenty of testing needed when we get something up and running. But this is probably months away.

FYI I' one of Red Hat Enterprise Linux QA guys. Kernel is not my focus but I'll see if I can help with testing when the time comes.

**Comment by shinglyu** [comment]
@patjak Thanks, I'll try to read your source code to get started.
